import Head from "next/head";
import { Modal } from '@mui/material';
import { createContext } from 'react';
import Signin from "../components/signin";
import Header from "../components/header";
import Signup from "../components/signup";
import Explore from '../components/explore';
import { useState, useEffect } from 'react';
import TopButton from "../components/topButton";
import MobileMenu from '../components/mobileMenu';
import { IonCol, IonGrid, IonRow } from '../functions';
import SwipeableDrawer from '@mui/material/SwipeableDrawer';
import ScrollToDiscover from '../components/scrollToDiscover';

export const appContext = createContext<any>({});

export default function Home() {
  type Anchor = 'left';
  const [width, setWidth] = useState<any>(0);
  const [height, setHeight] = useState<any>(0);
  const [open, setOpen] = useState<any>(false);
  const [form, setForm] = useState<any>(`signup`);
  const [menu, setMenu] = useState<any>({left: false});

  const toggleDrawer = (anchor: Anchor, open: boolean) => (event: React.KeyboardEvent | React.MouseEvent) => {
    anchor = `left`
      if (event &&
        event.type === 'keydown' &&
        ((event as React.KeyboardEvent).key === 'Tab' ||
          (event as React.KeyboardEvent).key === 'Shift')
      ) {
        return;
      }
      setMenu({ ...menu, [anchor]: open });
    };

  useEffect(() => {
    document.querySelectorAll(`.regBtn`).forEach(regBtn => regBtn.addEventListener(`click`, event => {
      switch ((event.target as HTMLButtonElement).id) {
        case `signupBtn`:
          setForm(`signup`);
          document.body.scrollTop = 1250;
          document.documentElement.scrollTop = 1250;
          break;
        case `signinBtn`:
          setForm(`signin`);          
          document.body.scrollTop = 1250;
          document.documentElement.scrollTop = 1250;
          break;
      }      
    }));
    const windowEvents = () => {
      setWidth(window.innerWidth);
      setHeight(window.innerHeight);
    };
    window.addEventListener('resize', () => windowEvents());
    window.addEventListener('scroll', () => windowEvents());
    return () => {
      window.removeEventListener('resize', () => windowEvents());
      window.removeEventListener('scroll', () => windowEvents());
    }
  }, [setWidth, setHeight, setForm]);

  return (
    <appContext.Provider value={{width, height, form}}>
      <div className="home">
        <Head>
          <title>Next.js Starter | Rakib Ahmed</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/GherkinLogo.svg" />
        </Head>
        <Header />
        <TopButton />
        <main id="mainSection">
          <div className="sideMenu">
            <div className="hamburger" title="Menu" onClick={toggleDrawer(`left`, true)}>
              <span className="top"></span>
              <span className="middle"></span>
              <span className="bottom"></span>
            </div>
            <SwipeableDrawer anchor={`left`} open={menu[`left`]} onClose={toggleDrawer(`left`, false)} onOpen={toggleDrawer(`left`, true)}>
              <MobileMenu />
            </SwipeableDrawer>
            <div className="search" title="Search" onClick={(event) => setOpen(true)}>
              <i className="fas fa-search"></i>
            </div>
            <Modal open={open} onClose={(event) => setOpen(false)} aria-labelledby="modal-modal-title" aria-describedby="modal-modal-description">
                <div className="innerModal">
                    <div className="innerContent">
                      <span className="searchText"><i className="fas fa-search"></i> Search</span>
                      <input type="text" placeholder='Search' className='searchField'/>
                    </div>
                </div>
              </Modal>
          </div>
          <div className="innerMain">
            <div className="mainBanner">
              <div className="textCol">
                <IonGrid>
                  <IonRow>
                    <IonCol size='1' id='mainspacercol' />
                    <IonCol class="mainSpace">
                      <h1>Next.js <span className={`bottomText`}>{width > 0 && width < 1238 ? `start` : `starter`} <span className="primaryVariant">file</span>.</span></h1>   
                      <p>Created a successful Next.js with Sass/TypeScript starter template ready made for deployment to Heroku with all the packages and dependencies I normally use. Will probably use this to make my new updated portfolio.</p>
                    </IonCol>
                  </IonRow>
                </IonGrid>
              </div>
            </div>
          </div>
          <ScrollToDiscover />
          <Explore />
        </main>
        <div className="sectionEndText">DESIGN / TEST / DEVELOPMENT</div>
        {form === `signup` ? <Signup /> : <Signin />}
        <div className="sectionEndText">DESIGN / TEST / DEVELOPMENT</div>
      </div>
    </appContext.Provider>
  );
}
